---
- name: "Blanking: Helpers"
  become: true
  copy:
    dest: /usr/local/bin/{{ item }}
    group: root
    mode: 'u=rwx,go=rx'
    owner: root
    src: "{{ item }}"
  with_items:
    - display_off.sh
    - display_on.sh
  when: ansible_lsb.id == 'Raspbian'

- name: "Blanking: Display off"
  become: true
  cron:
    cron_file: display_off
    hour: "{{ kiosk_display_off.hour }}"
    job: /usr/local/bin/display_off.sh
    minute: "{{ kiosk_display_off.minute }}"
    name: display_off
    user: "{{ kiosk_user }}"
    weekday: "{{ kiosk_display_off.weekday }}"
  when: ansible_lsb.id == 'Raspbian'

- name: "Blanking: Display On"
  become: true
  cron:
    cron_file: display_on
    hour: "{{ kiosk_display_on.hour }}"
    job: /usr/local/bin/display_on.sh
    minute: "{{ kiosk_display_on.minute }}"
    name: display_on
    user: "{{ kiosk_user }}"
    weekday: "{{ kiosk_display_on.weekday }}"
  when: ansible_lsb.id == 'Raspbian'
