---
- name: "Browser: Helper scripts"
  become: true
  copy:
    dest: /usr/local/bin/{{ item }}
    group: root
    mode: 'u=rwx,go=rx'
    owner: root
    src: "{{ item }}"
  with_items:
  - browser_refresh.sh

- name: "Browser: Auto Refresh"
  become: true
  cron:
    cron_file: browser_refresh
    hour: "{{ kiosk_display_refresh.hour }}"
    job: /usr/local/bin/browser_refresh.sh
    minute: "{{ kiosk_display_refresh.minute }}"
    name: browser_refresh
    user: "{{ kiosk_user }}"
    weekday: "{{ kiosk_display_refresh.weekday }}"

