---
# Based on https://naftuli.wtf/2017/12/28/systemd-user-environment/
# until support for systemd session management is added to LXDE (i.e. systemd controls the instatiation of lxsession)
- name: "Browser: Helper scripts"
  become: true
  copy:
    dest: /usr/local/bin/{{ item }}
    group: root
    mode: 'u=rwx,go=rx'
    owner: root
    src: "{{ item }}"
  with_items:
    - systemd-user-graphical-login.sh

- name: Systemd Kiosk User Services Directory
  become: true
  file:
    path: "{{ kiosk_user_home }}/.config/systemd/user"
    mode: "u=rwx,go="
    owner: "{{ kiosk_user }}"
    group: "{{ kiosk_user }}"
    state: directory

- name: Systemd Kiosk User Task Files
  become: true
  copy:
    dest: "{{ kiosk_user_home }}/.config/systemd/user/{{ item }}"
    group: "{{ kiosk_user }}"
    owner: "{{ kiosk_user }}"
    mode: "u=rw,go="
    src: "{{ item }}"
  loop:
    - browser-fullscreen.service
    - browser-fullscreen.timer
    - user-graphical-login.target
  notify:
    - restart LightDM

- name: Systemd Kiosk User Task Files
  become: true
  template:
    dest: "{{ kiosk_user_home }}/.config/systemd/user/{{ item | regex_replace('\\.user\\.j2','') }}"
    group: "{{ kiosk_user }}"
    owner: "{{ kiosk_user }}"
    mode: "u=rw,go="
    src: "{{ item }}"
  loop:
    - browser-refresh-off.timer.user.j2
    - browser-refresh-off.service.user.j2
    - browser-refresh.service.user.j2
    - browser-refresh-on.timer.user.j2
    - browser-refresh-on.service.user.j2
    - browser-tab-switch.timer.user.j2
    - browser-tab-switch.service.user.j2
    - disable-screensaver.service.user.j2
  notify:
    - restart LightDM

- name: Systemd Kiosk User Tasks
  become: true
  become_user: "{{ kiosk_user }}"
  systemd:
    daemon_reload: true
    enabled: true
    name: "{{ item }}"
    scope: user
  loop:
    - browser-fullscreen.timer
    - browser-refresh-off.timer
    - browser-refresh-on.timer
    - browser-tab-switch.timer
    - disable-screensaver.service
  notify:
    - restart LightDM
