---
- name: Keyboard blanking control
  become: true
  template:
    dest: /etc/kbd/config
    group: root
    mode: "u=rw,go=r"
    owner: root
    src: kbd.config.j2
  when:
    - (ansible_distribution | lower) == 'Debian'
    - (ansible_distribution_major_version | int) < 9
  notify: restart kbd

