---
- include: kiosk.yml
- name: "Kiosk: Browser Specific Vars"
  include_vars: "{{ kiosk_browser }}.yml"
- include: kbd.yml
- include: desktop.yml

- include: "{{ kiosk_browser }}.yml"
  when: kiosk_browser in ['chromium', 'epiphany', 'firefox', 'midori']

- include: browser_helpers.yml
- include: display.yml
- include: debug_console.yml
