---
- name: Console Setup Packgages
  become: true
  apt:
    name: "{{ keyboard_packages }}"
    state: present
  notify: restart keyboard service

- name: Configure Keyboard (Debian)
  become: true
  template:
    dest: /etc/default/keyboard
    group: root
    mode: 'u=rw,go=r'
    owner: root
    src: keyboard.default.j2
  when: ansible_os_family == 'Debian'
  notify: restart keyboard service
