---
kiosk_user: kiosk
kiosk_user_home: /home/{{ kiosk_user }}
kiosk_urls:
  - https://www.google.co.uk/
  - https://github.com/bdellegrazie/rpi-dashboard/
kiosk_environment: {}

kiosk_kbd_blank_time: 0
kiosk_kbd_blank_dpms: 'off'
kiosk_kbd_powerdown_time: 0

kiosk_autostart_optional: []

kiosk_display_off_manage: false
kiosk_display_off_cmd: "/usr/bin/vcgencmd display_power 0"
kiosk_display_off_calendar:
  - "Mon..Fri *-*-* 18:00:00"
kiosk_display_on_manage: false
kiosk_display_on_cmd: "/usr/bin/vcgencmd display_power 1"
kiosk_display_on_calendar:
  - "Mon..Fri *-*-* 08:00:00"

kiosk_browser: epiphany
kiosk_browser_width: 1920
kiosk_browser_height: 1080
kiosk_browser_screen_x: 0
kiosk_browser_screen_y: 0
kiosk_browser_sizemode: fullscreen

kiosk_browser_chrome_packages:
  - chromium
kiosk_browser_chrome_bin: /usr/bin/chromium

# Sequence of xte keys to switch tabs
kiosk_browser_tab_switch_keys:
  - 'keydown Control_L'
  - 'keydown Page_Down'
  - 'usleep 200'
  - 'keyup Page_Down'
  - 'keyup Control_L'

kiosk_browser_refresh_keys:
  - 'key F5'

kiosk_browser_tab_switch_calendar:
  - "Mon..Fri *-*-* 08..18:*:00/15"

kiosk_browser_refresh_on_calendar:
  - "Mon..Fri *-*-* 08..18:00/5:00"

# on time + (#sites * delay per sec)
kiosk_browser_refresh_off_calendar:
  - "Mon..Fri *-*-* 08..18:00/5:30"
