---
- name: Configure Timesyncd
  become: true
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: "u=rw,go=r"
    owner: root
    group: root
  notify:
    - Restart Timesyncd

- name: Timesyncd Service
  become: true
  systemd:
    name: systemd-timesyncd.service
    daemon_reload: true
    enabled: "{{ timesync_service_enabled | bool }}"
    state: "{{ timesync_service_state }}"
  when: timesync_service_manage | bool
